### ISSUE TITLE
How to implement non JSON services?

### ISSUE THREAD

**Issue by sriranga19** [ogrebgr/android_volley_examples#14]
Hi,
Thanks for sharing such a good library. I used this in some android apps contains JSON Request and Response but now i am working on GraphQL so, it is different from JSON. Do you have chance to share some sample code how to implement volley using GraphQL

**Comment by ogrebgr** [comment]
Hi,
I am afraid that I am no longer using Volley for HTTP library (I am now using OkHttp3) and this project is no longer supported. In general Volley can be used with all kind of content including GraphQL but I have no experience with it...

**Comment by sriranga19** [comment]
Thanks for your quick response. I will try to find a way.
